baseurl: https://jidzhang.github.io
languageCode: zh-cn
defaultContentLanguage: zh
title: 疯狂的键盘
theme: PaperMod

params:
  description: 爱软件爱开发
  author: Jid
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: false

  homeInfoParams:
    Title: "疯狂的键盘"
    Content: "爱软件爱开发"

menu:
  main:
    - name: 首页
      url: /
      weight: 1
    - name: 文章
      url: /posts/
      weight: 2
    - name: 分类
      url: /categories/
      weight: 3
    - name: 归档
      url: /archives/
      weight: 4
    - name: 关于
      url: /about/
      weight: 5

markup:
  highlight:
    noClasses: false
    style: onedark
